name: manage-azure-policy-5e7d820a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/asr_policy_01cd36c3-505e-4111-8bb4-a7839850a08a/**'
#      - 'policies/Configure_disaster_recovery_on_virtual_machines_by_enabling_replication_via_Azure_Site_Recovery_ac34a73f-9fa5-4067-9247-a3ecae514468/**'
#      - .github/workflows/manage-azure-policy-5e7d820a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5e7d820a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/asr_policy_01cd36c3-505e-4111-8bb4-a7839850a08a/**
          policies/Configure_disaster_recovery_on_virtual_machines_by_enabling_replication_via_Azure_Site_Recovery_ac34a73f-9fa5-4067-9247-a3ecae514468/**
